// <auto-generated />
using DAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DbContextBase))]
    [Migration("20230604081348_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TailLength")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Name = "Luntik",
                            Color = "Red",
                            TailLength = 10,
                            Weight = 80
                        },
                        new
                        {
                            Name = "Doggy",
                            Color = "Purple",
                            TailLength = 15,
                            Weight = 33
                        },
                        new
                        {
                            Name = "Kesha",
                            Color = "Black",
                            TailLength = 20,
                            Weight = 5
                        },
                        new
                        {
                            Name = "Vupsen",
                            Color = "Green",
                            TailLength = 50,
                            Weight = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
